site:                      Thibault Milan
# General Settings
url:                       thibaultmilan.com
baseurl:
timezone:                  Europe/Luxembourg

# Filtering Content
show_drafts:               null
limit_posts:               0
future:                    true
unpublished:               false

# Dev Settings
livereload:                true
openurl:                   true

# Collections Section
collections_dir:           content
collections:
  pages:
    output:                true
    permalink:             /:name
  posts:
    output:                true
    permalink:             /blog/:year/:month/:day/:title/
  projects:
    output:                true
    permalink:             /:collection/:slug

# Defaults for each collection type
defaults:
  - scope:
      path:                ""
    values:
      layout:              "default"
  - scope:
      path:                ""
      type:                "pages"
    values:
      layout:              "page"
  - scope:
      path:                ""
      type:                "posts"
    values:
      layout:              "post"
  - scope:
      path:                ""
      type:                "projects"
    values:
      layout:              "project"

# Conversion
markdown:                  kramdown
highlighter:               rouge
lsi:                       false
exceprt_separator:         "\n\n"
incremental:               false

# Markdown Processors
kramdown:
  input:                   GFM
  syntax_highlighter_opts:
    span:
      line_numbers:        true
    block:
      line_numbers:        true
      start_line:          1

# Sass Config
sass:
  style:                   compressed

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-twitter-plugin
  - jekyll_oembed

# Pagination Settings
pagination:
  enabled:                 true
  debug:                   true
  collection:              'post'
  per_page:                10
  permalink:               '/page/:num'
  title:                   ':title - page :num'
  limit:                   30
  sort_field:              'date'
  sort_reverse:            true
  category:                'posts'
  tag:                     ''
  locale:                  ''
  trail:
    before:                2
    after:                 2
  extension:               html
  indexpage:               'index'

# Handling Reading
include:                   [".htaccess"]
exclude:                   [".lfsconfig", ".gitignore", ".gitattributes", ".sass-cache/", ".jekyll-cache/", "gemfiles/", "Gemfile", "Gemfile.lock", "node_modules/", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:                [".git", ".svn"]
encoding:                  "utf-8"
markdown_ext:              "markdown,mkdown,mkdn,mkd,md"
strict_front_matter:       false
