site:                      Thibault Milan
# General Settings
url:                       thibaultmilan.com
title:                     Thibault Milan's weblog
description:               Find out what I've been up through my latest tech post
baseurl:
timezone:                  Europe/Luxembourg
author:                    Thibault Milan
accent_color:             "#066464"

# Feed configuration
feed:
  posts_limit:             20
  tags:                    true

# Filtering Content
show_drafts:               null
limit_posts:               0
future:                    true
unpublished:               false

# Dev Settings
livereload:                true
openurl:                   true

# Collections Section
collections_dir:           content
collections:
  pages:
    output:                true
    permalink:             /:name
  posts:
    output:                true
    permalink:             /blog/:year/:month/:day/:title/
  projects:
    output:                true
    permalink:             /:collection/:slug
  talks:
    output:                true
    permalink:             /:collection/:slug

# Defaults for each collection type
defaults:
  - scope:
      path:                ""
    values:
      layout:              "default"
  - scope:
      path:                ""
      type:                "pages"
    values:
      layout:              "page"
  - scope:
      path:                ""
      type:                "posts"
    values:
      layout:              "post"
  - scope:
      path:                ""
      type:                "projects"
    values:
      layout:              "project"
  - scope:
      path:                ""
      type:                "talks"
    values:
      layout:              "talk"

# Conversion
markdown:                  kramdown
highlighter:               rouge
lsi:                       true
incremental:               false
excerpt_separator:         "<!--more-->"
# Markdown Processors
kramdown:
  input:                   GFM
  hard_wrap:               true
  syntax_highlighter_opts:
    span:
      line_numbers:        false
    block:
      line_numbers:        true
      start_line:          1
  smart_quotes:            apos,apos,quot,quot
  typographic_symbols:     {hellip: ...}

# Sass Config
sass:
  style:                   compressed

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-twitter-plugin
  - jekyll-feed

# Pagination Settings (jekyll-paginate - posts only)
paginate: 10
paginate_path: "/blog/page/:num/"

# Handling Reading
include:                   [".htaccess"]
exclude:                   [".lfsconfig", ".gitignore", ".gitattributes", ".sass-cache/", ".jekyll-cache/", "gemfiles/", "Gemfile", "Gemfile.lock", "node_modules/", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:                [".git", ".svn"]
encoding:                  "utf-8"
markdown_ext:              "markdown,mkdown,mkdn,mkd,md"
strict_front_matter:       false
