site: Thibault Milan

url: thibaultmilan.com
baseurl:
future: true

collections_dir: content
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  talks:
    output: true
    permalink: /:collection/:title
  projects:
    output: true
    permalink: /:collection/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "talk"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  style: compressed

plugins:
  - jekyll-sitemap

paginate: 7
paginate_path: "/blog/page-:num/"

exclude:
    - .lfsconfig
    - .gitignore
    - .gitattributes
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
timezone: Europe/Luxembourg
